### ISSUE TITLE
Raspberry pi IP connection issues

### ISSUE THREAD

**Issue by taffs08** [RamyE/SFU_ML#22]
Hi Ramy,

I was able to obtain the IP address using my wifi router App, but when I try check in cmd.exe and connecting to session, I am getting the following errors attached. Please may request troubeshooting assistance. 

![error](https://user-images.githubusercontent.com/101284094/157511141-42600ca7-b169-4971-aea8-c3affe1a7947.PNG)

![error2](https://user-images.githubusercontent.com/101284094/157511166-84df3daa-0c61-4119-b67f-578d9a52e003.PNG)

![error3](https://user-images.githubusercontent.com/101284094/157511202-8afb0b49-e842-4564-816d-889b2494b6a0.PNG)

>

**Comment by RamyE** [comment]
It's likely that ssh is not enabled on the raspberry pi, or you have
another RPi on the network?

One way to confirm you're trying to access the right one is to unplug it
and try the ssh command again. It's the right one if you get no route to
host rather than connection refused.

If the ssh is not enabled, confirm step 1.1.3 in the manual

**Comment by taffs08** [comment]
Thanks, the ssh file was missing. Now working
